<?php

return [
    "AF" => [
        'id' => 1,
        'phone_code' => '+93',
        'name' => 'Afghanistan',
        'iso' => 'AF',
        'state_status' => 1,
    ],
    "AL" => [
        'id' => 2,
        'phone_code' => '+355',
        'name' => 'Albania',
        'iso' => 'AL',
        'state_status' => 1,
    ],
    "DZ" => [
        'id' => 3,
        'phone_code' => '+213',
        'name' => 'Algeria',
        'iso' => 'DZ',
        'state_status' => 1,
    ],
    "AS" => [
        'id' => 4,
        'phone_code' => '+1684',
        'name' => 'American Samoa',
        'iso' => 'AS',
        'state_status' => 1,
    ],
    "AD" => [
        'id' => 5,
        'phone_code' => '+376',
        'name' => 'Andorra',
        'iso' => 'AD',
        'state_status' => 1,
    ],
    "AO" => [
        'id' => 6,
        'phone_code' => '+244',
        'name' => 'Angola',
        'iso' => 'AO',
        'state_status' => 1,
    ],
    "AI" => [
        'id' => 7,
        'phone_code' => '+1264',
        'name' => 'Anguilla',
        'iso' => 'AI',
        'state_status' => 1,
    ],
    "AG" => [
        'id' => 8,
        'phone_code' => '+1268',
        'name' => 'Antigua and Barbuda',
        'iso' => 'AG',
        'state_status' => 1,
    ],
    "AR" => [
        'id' => 9,
        'phone_code' => '+54',
        'name' => 'Argentina',
        'iso' => 'AR',
        'state_status' => 1,
    ],
    "AM" => [
        'id' => 10,
        'phone_code' => '+374',
        'name' => 'Armenia',
        'iso' => 'AM',
        'state_status' => 1,
    ],
    "AU" => [
        'id' => 11,
        'phone_code' => '+61',
        'name' => 'Australia',
        'iso' => 'AU',
        'state_status' => 1,
    ],
    "AT" => [
        'id' => 12,
        'phone_code' => '+43',
        'name' => 'Austria',
        'iso' => 'AT',
        'state_status' => 1,
    ],
    "AZ" => [
        'id' => 13,
        'phone_code' => '+994',
        'name' => 'Azerbaijan',
        'iso' => 'AZ',
        'state_status' => 1,
    ],
    "BS" => [
        'id' => 14,
        'phone_code' => '+1242',
        'name' => 'Bahamas',
        'iso' => 'BS',
        'state_status' => 1,
    ],
    "BH" => [
        'id' => 15,
        'phone_code' => '+973',
        'name' => 'Bahrain',
        'iso' => 'BH',
        'state_status' => 1,
    ],
    "BD" => [
        'id' => 16,
        'phone_code' => '+880',
        'name' => 'Bangladesh',
        'iso' => 'BD',
        'state_status' => 1,
    ],
    "BB" => [
        'id' => 17,
        'phone_code' => '+1246',
        'name' => 'Barbados',
        'iso' => 'BB',
        'state_status' => 1,
    ],
    "BY" => [
        'id' => 18,
        'phone_code' => '+375',
        'name' => 'Belarus',
        'iso' => 'BY',
        'state_status' => 1,
    ],
    "BE" => [
        'id' => 19,
        'phone_code' => '+32',
        'name' => 'Belgium',
        'iso' => 'BE',
        'state_status' => 1,
    ],
    "BZ" => [
        'id' => 20,
        'phone_code' => '+501',
        'name' => 'Belize',
        'iso' => 'BZ',
        'state_status' => 1,
    ],
    "BM" => [
        'id' => 21,
        'phone_code' => '+1441',
        'name' => 'Bermuda',
        'iso' => 'BM',
        'state_status' => 1,
    ],
    "BT" => [
        'id' => 22,
        'phone_code' => '+975',
        'name' => 'Bhutan',
        'iso' => 'BT',
        'state_status' => 1,
    ],
    "BO" => [
        'id' => 23,
        'phone_code' => '+591',
        'name' => 'Bolivia',
        'iso' => 'BO',
        'state_status' => 1,
    ],
    "BA" => [
        'id' => 24,
        'phone_code' => '+387',
        'name' => 'Bosnia and Herzegovina',
        'iso' => 'BA',
        'state_status' => 1,
    ],
    "BW" => [
        'id' => 25,
        'phone_code' => '+267',
        'name' => 'Botswana',
        'iso' => 'BW',
        'state_status' => 1,
    ],
    "BR" => [
        'id' => 26,
        'phone_code' => '+55',
        'name' => 'Brazil',
        'iso' => 'BR',
        'state_status' => 1,
    ],
    "BN" => [
        'id' => 27,
        'phone_code' => '+673',
        'name' => 'Brunei Darussalam',
        'iso' => 'BN',
        'state_status' => 1,
    ],
    "BG" => [
        'id' => 28,
        'phone_code' => '+359',
        'name' => 'Bulgaria',
        'iso' => 'BG',
        'state_status' => 1,
    ],
    "BF" => [
        'id' => 29,
        'phone_code' => '+226',
        'name' => 'Burkina Faso',
        'iso' => 'BF',
        'state_status' => 1,
    ],
    "BI" => [
        'id' => 30,
        'phone_code' => '+257',
        'name' => 'Burundi',
        'iso' => 'BI',
        'state_status' => 1,
    ],
    "KH" => [
        'id' => 31,
        'phone_code' => '+855',
        'name' => 'Cambodia',
        'iso' => 'KH',
        'state_status' => 1,
    ],
    "CM" => [
        'id' => 32,
        'phone_code' => '+237',
        'name' => 'Cameroon',
        'iso' => 'CM',
        'state_status' => 1,
    ],
    "CA" => [
        'id' => 33,
        'phone_code' => '+1',
        'name' => 'Canada',
        'iso' => 'CA',
        'state_status' => 1,
    ],
    "CV" => [
        'id' => 34,
        'phone_code' => '+238',
        'name' => 'Cape Verde',
        'iso' => 'CV',
        'state_status' => 1,
    ],
    "KY" => [
        'id' => 35,
        'phone_code' => '+1345',
        'name' => 'Cayman Islands',
        'iso' => 'KY',
        'state_status' => 1,
    ],
    "CF" => [
        'id' => 36,
        'phone_code' => '+236',
        'name' => 'Central African Republic',
        'iso' => 'CF',
        'state_status' => 1,
    ],
    "TD" => [
        'id' => 37,
        'phone_code' => '+235',
        'name' => 'Chad',
        'iso' => 'TD',
        'state_status' => 1,
    ],
    "CL" => [
        'id' => 38,
        'phone_code' => '+56',
        'name' => 'Chile',
        'iso' => 'CL',
        'state_status' => 1,
    ],
    "CN" => [
        'id' => 39,
        'phone_code' => '+86',
        'name' => 'China',
        'iso' => 'CN',
        'state_status' => 1,
    ],
    "CO" => [
        'id' => 40,
        'phone_code' => '+57',
        'name' => 'Colombia',
        'iso' => 'CO',
        'state_status' => 1,
    ],
    "KM" => [
        'id' => 41,
        'phone_code' => '+269',
        'name' => 'Comoros',
        'iso' => 'KM',
        'state_status' => 1,
    ],
    "CD" => [
        'id' => 42,
        'phone_code' => '+242',
        'name' => 'Congo (DRC)',
        'iso' => 'CD',
        'state_status' => 1,
    ],
    "CG" => [
        'id' => 43,
        'phone_code' => '+242',
        'name' => 'Congo',
        'iso' => 'CG',
        'state_status' => 1,
    ],
    "CK" => [
        'id' => 44,
        'phone_code' => '+682',
        'name' => 'Cook Islands',
        'iso' => 'CK',
        'state_status' => 1,
    ],
    "CR" => [
        'id' => 45,
        'phone_code' => '+506',
        'name' => 'Costa Rica',
        'iso' => 'CR',
        'state_status' => 1,
    ],
    "CI" => [
        'id' => 46,
        'phone_code' => '+225',
        'name' => 'Cote D\'Ivoire',
        'iso' => 'CI',
        'state_status' => 1,
    ],
    "HR" => [
        'id' => 47,
        'phone_code' => '+385',
        'name' => 'Croatia',
        'iso' => 'HR',
        'state_status' => 1,
    ],
    "CU" => [
        'id' => 48,
        'phone_code' => '+53',
        'name' => 'Cuba',
        'iso' => 'CU',
        'state_status' => 1,
    ],
    "CY" => [
        'id' => 49,
        'phone_code' => '+357',
        'name' => 'Cyprus',
        'iso' => 'CY',
        'state_status' => 1,
    ],
    "CZ" => [
        'id' => 50,
        'phone_code' => '+420',
        'name' => 'Czech Republic',
        'iso' => 'CZ',
        'state_status' => 1,
    ],
    "DK" => [
        'id' => 51,
        'phone_code' => '+45',
        'name' => 'Denmark',
        'iso' => 'DK',
        'state_status' => 1,
    ],
    "DJ" => [
        'id' => 52,
        'phone_code' => '+253',
        'name' => 'Djibouti',
        'iso' => 'DJ',
        'state_status' => 1,
    ],
    "DM" => [
        'id' => 53,
        'phone_code' => '+1767',
        'name' => 'Dominica',
        'iso' => 'DM',
        'state_status' => 1,
    ],
    "DO" => [
        'id' => 54,
        'phone_code' => '+1809',
        'name' => 'Dominican Republic',
        'iso' => 'DO',
        'state_status' => 1,
    ],
    "TL" => [
        'id' => 55,
        'phone_code' => '+670',
        'name' => 'East Timor',
        'iso' => 'TL',
        'state_status' => 1,
    ],
    "EC" => [
        'id' => 56,
        'phone_code' => '+593',
        'name' => 'Ecuador',
        'iso' => 'EC',
        'state_status' => 1,
    ],
    "EG" => [
        'id' => 57,
        'phone_code' => '+20',
        'name' => 'Egypt',
        'iso' => 'EG',
        'state_status' => 1,
    ],
    "SV" => [
        'id' => 58,
        'phone_code' => '+503',
        'name' => 'El Salvador',
        'iso' => 'SV',
        'state_status' => 1,
    ],
    "GQ" => [
        'id' => 59,
        'phone_code' => '+240',
        'name' => 'Equatorial Guinea',
        'iso' => 'GQ',
        'state_status' => 1,
    ],
    "ER" => [
        'id' => 60,
        'phone_code' => '+291',
        'name' => 'Eritrea',
        'iso' => 'ER',
        'state_status' => 1,
    ],
    "EE" => [
        'id' => 61,
        'phone_code' => '+372',
        'name' => 'Estonia',
        'iso' => 'EE',
        'state_status' => 1,
    ],
    "ET" => [
        'id' => 62,
        'phone_code' => '+251',
        'name' => 'Ethiopia',
        'iso' => 'ET',
        'state_status' => 1,
    ],
    "FK" => [
        'id' => 63,
        'phone_code' => '+500',
        'name' => 'Falkland Islands (Malvinas)',
        'iso' => 'FK',
        'state_status' => 1,
    ],
    "FO" => [
        'id' => 64,
        'phone_code' => '+298',
        'name' => 'Faroe Islands',
        'iso' => 'FO',
        'state_status' => 1,
    ],
    "FJ" => [
        'id' => 65,
        'phone_code' => '+679',
        'name' => 'Fiji',
        'iso' => 'FJ',
        'state_status' => 1,
    ],
    "FI" => [
        'id' => 66,
        'phone_code' => '+358',
        'name' => 'Finland',
        'iso' => 'FI',
        'state_status' => 1,
    ],
    "FR" => [
        'id' => 67,
        'phone_code' => '+33',
        'name' => 'France',
        'iso' => 'FR',
        'state_status' => 1,
    ],
    "GA" => [
        'id' => 68,
        'phone_code' => '+241',
        'name' => 'Gabon',
        'iso' => 'GA',
        'state_status' => 1,
    ],
    "GM" => [
        'id' => 69,
        'phone_code' => '+220',
        'name' => 'Gambia',
        'iso' => 'GM',
        'state_status' => 1,
    ],
    "GE" => [
        'id' => 70,
        'phone_code' => '+995',
        'name' => 'Georgia',
        'iso' => 'GE',
        'state_status' => 1,
    ],
    "DE" => [
        'id' => 71,
        'phone_code' => '+49',
        'name' => 'Germany',
        'iso' => 'DE',
        'state_status' => 1,
    ],
    "GH" => [
        'id' => 72,
        'phone_code' => '+233',
        'name' => 'Ghana',
        'iso' => 'GH',
        'state_status' => 1,
    ],
    "GI" => [
        'id' => 73,
        'phone_code' => '+350',
        'name' => 'Gibraltar',
        'iso' => 'GI',
        'state_status' => 1,
    ],
    "GR" => [
        'id' => 74,
        'phone_code' => '+30',
        'name' => 'Greece',
        'iso' => 'GR',
        'state_status' => 1,
    ],
    "GL" => [
        'id' => 75,
        'phone_code' => '+299',
        'name' => 'Greenland',
        'iso' => 'GL',
        'state_status' => 1,
    ],
    "GD" => [
        'id' => 76,
        'phone_code' => '+1473',
        'name' => 'Grenada',
        'iso' => 'GD',
        'state_status' => 1,
    ],
    "GP" => [
        'id' => 77,
        'phone_code' => '+590',
        'name' => 'Guadeloupe',
        'iso' => 'GP',
        'state_status' => 1,
    ],
    "GU" => [
        'id' => 78,
        'phone_code' => '+1671',
        'name' => 'Guam',
        'iso' => 'GU',
        'state_status' => 1,
    ],
    "GT" => [
        'id' => 79,
        'phone_code' => '+502',
        'name' => 'Guatemala',
        'iso' => 'GT',
        'state_status' => 1,
    ],
    "GN" => [
        'id' => 80,
        'phone_code' => '+224',
        'name' => 'Guinea',
        'iso' => 'GN',
        'state_status' => 1,
    ],
    "GW" => [
        'id' => 81,
        'phone_code' => '+245',
        'name' => 'Guinea-Bissau',
        'iso' => 'GW',
        'state_status' => 1,
    ],
    "GY" => [
        'id' => 82,
        'phone_code' => '+592',
        'name' => 'Guyana',
        'iso' => 'GY',
        'state_status' => 1,
    ],
    "HT" => [
        'id' => 83,
        'phone_code' => '+509',
        'name' => 'Haiti',
        'iso' => 'HT',
        'state_status' => 1,
    ],
    "VA" => [
        'id' => 84,
        'phone_code' => '+39',
        'name' => 'Holy See (Vatican City State)',
        'iso' => 'VA',
        'state_status' => 1,
    ],
    "HN" => [
        'id' => 85,
        'phone_code' => '+504',
        'name' => 'Honduras',
        'iso' => 'HN',
        'state_status' => 1,
    ],
    "HK" => [
        'id' => 86,
        'phone_code' => '+852',
        'name' => 'Hong Kong',
        'iso' => 'HK',
        'state_status' => 1,
    ],
    "HU" => [
        'id' => 87,
        'phone_code' => '+36',
        'name' => 'Hungary',
        'iso' => 'HU',
        'state_status' => 1,
    ],
    "IS" => [
        'id' => 88,
        'phone_code' => '+354',
        'name' => 'Iceland',
        'iso' => 'IS',
        'state_status' => 1,
    ],
    "IN" => [
        'id' => 89,
        'phone_code' => '+91',
        'name' => 'India',
        'iso' => 'IN',
        'state_status' => 1,
    ],
    "ID" => [
        'id' => 90,
        'phone_code' => '+62',
        'name' => 'Indonesia',
        'iso' => 'ID',
        'state_status' => 1,
    ],
    "IR" => [
        'id' => 91,
        'phone_code' => '+98',
        'name' => 'Iran',
        'iso' => 'IR',
        'state_status' => 1,
    ],
    "IQ" => [
        'id' => 92,
        'phone_code' => '+964',
        'name' => 'Iraq',
        'iso' => 'IQ',
        'state_status' => 1,
    ],
    "IE" => [
        'id' => 93,
        'phone_code' => '+353',
        'name' => 'Ireland',
        'iso' => 'IE',
        'state_status' => 1,
    ],
    "IL" => [
        'id' => 94,
        'phone_code' => '+972',
        'name' => 'Israel',
        'iso' => 'IL',
        'state_status' => 1,
    ],
    "IT" => [
        'id' => 95,
        'phone_code' => '+39',
        'name' => 'Italy',
        'iso' => 'IT',
        'state_status' => 1,
    ],
    "JM" => [
        'id' => 96,
        'phone_code' => '+1876',
        'name' => 'Jamaica',
        'iso' => 'JM',
        'state_status' => 1,
    ],
    "JP" => [
        'id' => 97,
        'phone_code' => '+81',
        'name' => 'Japan',
        'iso' => 'JP',
        'state_status' => 1,
    ],
    "JO" => [
        'id' => 98,
        'phone_code' => '+962',
        'name' => 'Jordan',
        'iso' => 'JO',
        'state_status' => 1,
    ],
    "KZ" => [
        'id' => 99,
        'phone_code' => '+7',
        'name' => 'Kazakhstan',
        'iso' => 'KZ',
        'state_status' => 1,
    ],
    "KE" => [
        'id' => 100,
        'phone_code' => '+254',
        'name' => 'Kenya',
        'iso' => 'KE',
        'state_status' => 1,
    ],
    "KI" => [
        'id' => 101,
        'phone_code' => '+686',
        'name' => 'Kiribati',
        'iso' => 'KI',
        'state_status' => 1,
    ],
    "KP" => [
        'id' => 102,
        'phone_code' => '+850',
        'name' => 'North Korea',
        'iso' => 'KP',
        'state_status' => 1,
    ],
    "KR" => [
        'id' => 103,
        'phone_code' => '+82',
        'name' => 'South Korea',
        'iso' => 'KR',
        'state_status' => 1,
    ],
    "KW" => [
        'id' => 104,
        'phone_code' => '+965',
        'name' => 'Kuwait',
        'iso' => 'KW',
        'state_status' => 1,
    ],
    "KG" => [
        'id' => 105,
        'phone_code' => '+996',
        'name' => 'Kyrgyzstan',
        'iso' => 'KG',
        'state_status' => 1,
    ],
    "LA" => [
        'id' => 106,
        'phone_code' => '+856',
        'name' => 'Laos',
        'iso' => 'LA',
        'state_status' => 1,
    ],
    "LV" => [
        'id' => 107,
        'phone_code' => '+371',
        'name' => 'Latvia',
        'iso' => 'LV',
        'state_status' => 1,
    ],
    "LB" => [
        'id' => 108,
        'phone_code' => '+961',
        'name' => 'Lebanon',
        'iso' => 'LB',
        'state_status' => 1,
    ],
    "LS" => [
        'id' => 109,
        'phone_code' => '+266',
        'name' => 'Lesotho',
        'iso' => 'LS',
        'state_status' => 1,
    ],
    "LR" => [
        'id' => 110,
        'phone_code' => '+231',
        'name' => 'Liberia',
        'iso' => 'LR',
        'state_status' => 1,
    ],
    "LY" => [
        'id' => 111,
        'phone_code' => '+218',
        'name' => 'Libyan',
        'iso' => 'LY',
        'state_status' => 1,
    ],
    "LI" => [
        'id' => 112,
        'phone_code' => '+423',
        'name' => 'Liechtenstein',
        'iso' => 'LI',
        'state_status' => 1,
    ],
    "LT" => [
        'id' => 113,
        'phone_code' => '+370',
        'name' => 'Lithuania',
        'iso' => 'LT',
        'state_status' => 1,
    ],
    "LU" => [
        'id' => 114,
        'phone_code' => '+352',
        'name' => 'Luxembourg',
        'iso' => 'LU',
        'state_status' => 1,
    ],
    "MO" => [
        'id' => 115,
        'phone_code' => '+853',
        'name' => 'Macao',
        'iso' => 'MO',
        'state_status' => 1,
    ],
    "MK" => [
        'id' => 116,
        'phone_code' => '+389',
        'name' => 'Macedonia',
        'iso' => 'MK',
        'state_status' => 1,
    ],
    "MG" => [
        'id' => 117,
        'phone_code' => '+261',
        'name' => 'Madagascar',
        'iso' => 'MG',
        'state_status' => 1,
    ],
    "MW" => [
        'id' => 118,
        'phone_code' => '+265',
        'name' => 'Malawi',
        'iso' => 'MW',
        'state_status' => 1,
    ],
    "MY" => [
        'id' => 119,
        'phone_code' => '+60',
        'name' => 'Malaysia',
        'iso' => 'MY',
        'state_status' => 1,
    ],
    "MV" => [
        'id' => 120,
        'phone_code' => '+960',
        'name' => 'Maldives',
        'iso' => 'MV',
        'state_status' => 1,
    ],
    "ML" => [
        'id' => 121,
        'phone_code' => '+223',
        'name' => 'Mali',
        'iso' => 'ML',
        'state_status' => 1,
    ],
    "MT" => [
        'id' => 122,
        'phone_code' => '+356',
        'name' => 'Malta',
        'iso' => 'MT',
        'state_status' => 1,
    ],
    "MQ" => [
        'id' => 123,
        'phone_code' => '+596',
        'name' => 'Martinique',
        'iso' => 'MQ',
        'state_status' => 1,
    ],
    "MR" => [
        'id' => 124,
        'phone_code' => '+222',
        'name' => 'Mauritania',
        'iso' => 'MR',
        'state_status' => 1,
    ],
    "MU" => [
        'id' => 125,
        'phone_code' => '+230',
        'name' => 'Mauritius',
        'iso' => 'MU',
        'state_status' => 1,
    ],
    "YT" => [
        'id' => 126,
        'phone_code' => '+269',
        'name' => 'Mayotte',
        'iso' => 'YT',
        'state_status' => 1,
    ],
    "MX" => [
        'id' => 127,
        'phone_code' => '+52',
        'name' => 'Mexico',
        'iso' => 'MX',
        'state_status' => 1,
    ],
    "FM" => [
        'id' => 128,
        'phone_code' => '+691',
        'name' => 'Micronesia',
        'iso' => 'FM',
        'state_status' => 1,
    ],
    "MD" => [
        'id' => 129,
        'phone_code' => '+373',
        'name' => 'Moldova',
        'iso' => 'MD',
        'state_status' => 1,
    ],
    "MC" => [
        'id' => 130,
        'phone_code' => '+377',
        'name' => 'Monaco',
        'iso' => 'MC',
        'state_status' => 1,
    ],
    "MN" => [
        'id' => 131,
        'phone_code' => '+976',
        'name' => 'Mongolia',
        'iso' => 'MN',
        'state_status' => 1,
    ],
    "MS" => [
        'id' => 132,
        'phone_code' => '+1664',
        'name' => 'Montserrat',
        'iso' => 'MS',
        'state_status' => 1,
    ],
    "MA" => [
        'id' => 133,
        'phone_code' => '+212',
        'name' => 'Morocco',
        'iso' => 'MA',
        'state_status' => 1,
    ],
    "MZ" => [
        'id' => 134,
        'phone_code' => '+258',
        'name' => 'Mozambique',
        'iso' => 'MZ',
        'state_status' => 1,
    ],
    "MM" => [
        'id' => 135,
        'phone_code' => '+95',
        'name' => 'Myanmar',
        'iso' => 'MM',
        'state_status' => 1,
    ],
    "NA" => [
        'id' => 136,
        'phone_code' => '+264',
        'name' => 'Namibia',
        'iso' => 'NA',
        'state_status' => 1,
    ],
    "NR" => [
        'id' => 137,
        'phone_code' => '+674',
        'name' => 'Nauru',
        'iso' => 'NR',
        'state_status' => 1,
    ],
    "NP" => [
        'id' => 138,
        'phone_code' => '+977',
        'name' => 'Nepal',
        'iso' => 'NP',
        'state_status' => 1,
    ],
    "NL" => [
        'id' => 139,
        'phone_code' => '+31',
        'name' => 'Netherlands',
        'iso' => 'NL',
        'state_status' => 1,
    ],
    "AN" => [
        'id' => 140,
        'phone_code' => '+599',
        'name' => 'Netherlands Antilles',
        'iso' => 'AN',
        'state_status' => 1,
    ],
    "NC" => [
        'id' => 141,
        'phone_code' => '+687',
        'name' => 'New Caledonia',
        'iso' => 'NC',
        'state_status' => 1,
    ],
    "NZ" => [
        'id' => 142,
        'phone_code' => '+64',
        'name' => 'New Zealand',
        'iso' => 'NZ',
        'state_status' => 1,
    ],
    "NI" => [
        'id' => 143,
        'phone_code' => '+505',
        'name' => 'Nicaragua',
        'iso' => 'NI',
        'state_status' => 1,
    ],
    "NE" => [
        'id' => 144,
        'phone_code' => '+227',
        'name' => 'Niger',
        'iso' => 'NE',
        'state_status' => 1,
    ],
    "NG" => [
        'id' => 145,
        'phone_code' => '+234',
        'name' => 'Nigeria',
        'iso' => 'NG',
        'state_status' => 1,
    ],
    "NU" => [
        'id' => 146,
        'phone_code' => '+683',
        'name' => 'Niue',
        'iso' => 'NU',
        'state_status' => 1,
    ],
    "NF" => [
        'id' => 147,
        'phone_code' => '+672',
        'name' => 'Norfolk Island',
        'iso' => 'NF',
        'state_status' => 1,
    ],
    "NO" => [
        'id' => 148,
        'phone_code' => '+47',
        'name' => 'Norway',
        'iso' => 'NO',
        'state_status' => 1,
    ],
    "OM" => [
        'id' => 149,
        'phone_code' => '+968',
        'name' => 'Oman',
        'iso' => 'OM',
        'state_status' => 1,
    ],
    "PK" => [
        'id' => 150,
        'phone_code' => '+92',
        'name' => 'Pakistan',
        'iso' => 'PK',
        'state_status' => 1,
    ],
    "PA" => [
        'id' => 151,
        'phone_code' => '+507',
        'name' => 'Panama',
        'iso' => 'PA',
        'state_status' => 1,
    ],
    "PG" => [
        'id' => 152,
        'phone_code' => '+675',
        'name' => 'Papua New Guinea',
        'iso' => 'PG',
        'state_status' => 1,
    ],
    "PY" => [
        'id' => 153,
        'phone_code' => '+595',
        'name' => 'Paraguay',
        'iso' => 'PY',
        'state_status' => 1,
    ],
    "PE" => [
        'id' => 154,
        'phone_code' => '+51',
        'name' => 'Peru',
        'iso' => 'PE',
        'state_status' => 1,
    ],
    "PH" => [
        'id' => 155,
        'phone_code' => '+63',
        'name' => 'Philippines',
        'iso' => 'PH',
        'state_status' => 1,
    ],
    "PN" => [
        'id' => 156,
        'phone_code' => '+0',
        'name' => 'Pitcairn Islands',
        'iso' => 'PN',
        'state_status' => 1,
    ],
    "PL" => [
        'id' => 157,
        'phone_code' => '+48',
        'name' => 'Poland',
        'iso' => 'PL',
        'state_status' => 1,
    ],
    "PT" => [
        'id' => 158,
        'phone_code' => '+351',
        'name' => 'Portugal',
        'iso' => 'PT',
        'state_status' => 1,
    ],
    "PR" => [
        'id' => 159,
        'phone_code' => '+1787',
        'name' => 'Puerto Rico',
        'iso' => 'PR',
        'state_status' => 1,
    ],
    "QA" => [
        'id' => 160,
        'phone_code' => '+974',
        'name' => 'Qatar',
        'iso' => 'QA',
        'state_status' => 1,
    ],
    "RE" => [
        'id' => 161,
        'phone_code' => '+262',
        'name' => 'Reunion',
        'iso' => 'RE',
        'state_status' => 1,
    ],
    "RO" => [
        'id' => 162,
        'phone_code' => '+40',
        'name' => 'Romania',
        'iso' => 'RO',
        'state_status' => 1,
    ],
    "RU" => [
        'id' => 163,
        'phone_code' => '+70',
        'name' => 'Russia',
        'iso' => 'RU',
        'state_status' => 1,
    ],
    "RW" => [
        'id' => 164,
        'phone_code' => '+250',
        'name' => 'Rwanda',
        'iso' => 'RW',
        'state_status' => 1,
    ],
    "WS" => [
        'id' => 165,
        'phone_code' => '+684',
        'name' => 'Samoa',
        'iso' => 'WS',
        'state_status' => 1,
    ],
    "SM" => [
        'id' => 166,
        'phone_code' => '+378',
        'name' => 'San Marino',
        'iso' => 'SM',
        'state_status' => 1,
    ],
    "ST" => [
        'id' => 167,
        'phone_code' => '+239',
        'name' => 'Sao Tome and Principe',
        'iso' => 'ST',
        'state_status' => 1,
    ],
    "SA" => [
        'id' => 168,
        'phone_code' => '+966',
        'name' => 'Saudi Arabia',
        'iso' => 'SA',
        'state_status' => 1,
    ],
    "SN" => [
        'id' => 169,
        'phone_code' => '+221',
        'name' => 'Senegal',
        'iso' => 'SN',
        'state_status' => 1,
    ],
    "CS" => [
        'id' => 170,
        'phone_code' => '+381',
        'name' => 'Serbia and Montenegro',
        'iso' => 'CS',
        'state_status' => 1,
    ],
    "SC" => [
        'id' => 171,
        'phone_code' => '+248',
        'name' => 'Seychelles',
        'iso' => 'SC',
        'state_status' => 1,
    ],
    "SL" => [
        'id' => 172,
        'phone_code' => '+232',
        'name' => 'Sierra Leone',
        'iso' => 'SL',
        'state_status' => 1,
    ],
    "SG" => [
        'id' => 173,
        'phone_code' => '+65',
        'name' => 'Singapore',
        'iso' => 'SG',
        'state_status' => 1,
    ],
    "SK" => [
        'id' => 174,
        'phone_code' => '+421',
        'name' => 'Slovakia',
        'iso' => 'SK',
        'state_status' => 1,
    ],
    "SI" => [
        'id' => 175,
        'phone_code' => '+386',
        'name' => 'Slovenia',
        'iso' => 'SI',
        'state_status' => 1,
    ],
    "SB" => [
        'id' => 176,
        'phone_code' => '+677',
        'name' => 'Solomon Islands',
        'iso' => 'SB',
        'state_status' => 1,
    ],
    "SO" => [
        'id' => 177,
        'phone_code' => '+252',
        'name' => 'Somalia',
        'iso' => 'SO',
        'state_status' => 1,
    ],
    "ZA" => [
        'id' => 178,
        'phone_code' => '+27',
        'name' => 'South Africa',
        'iso' => 'ZA',
        'state_status' => 1,
    ],
    "ES" => [
        'id' => 179,
        'phone_code' => '+34',
        'name' => 'Spain',
        'iso' => 'ES',
        'state_status' => 1,
    ],
    "LK" => [
        'id' => 180,
        'phone_code' => '+94',
        'name' => 'Sri Lanka',
        'iso' => 'LK',
        'state_status' => 1,
    ],
    "SH" => [
        'id' => 181,
        'phone_code' => '+290',
        'name' => 'St. Helena',
        'iso' => 'SH',
        'state_status' => 1,
    ],
    "KN" => [
        'id' => 182,
        'phone_code' => '+1869',
        'name' => 'St. Kitts & Nevis',
        'iso' => 'KN',
        'state_status' => 1,
    ],
    "LC" => [
        'id' => 183,
        'phone_code' => '+1758',
        'name' => 'St. Lucia',
        'iso' => 'LC',
        'state_status' => 1,
    ],
    "PM" => [
        'id' => 184,
        'phone_code' => '+508',
        'name' => 'St. Pierre and Miquelon',
        'iso' => 'PM',
        'state_status' => 1,
    ],
    "VC" => [
        'id' => 185,
        'phone_code' => '+1784',
        'name' => 'St. Vincent & Grenadines',
        'iso' => 'VC',
        'state_status' => 1,
    ],
    "SD" => [
        'id' => 186,
        'phone_code' => '+249',
        'name' => 'Sudan',
        'iso' => 'SD',
        'state_status' => 1,
    ],
    "SR" => [
        'id' => 187,
        'phone_code' => '+597',
        'name' => 'Suriname',
        'iso' => 'SR',
        'state_status' => 1,
    ],
    "SZ" => [
        'id' => 188,
        'phone_code' => '+268',
        'name' => 'Swaziland',
        'iso' => 'SZ',
        'state_status' => 1,
    ],
    "SE" => [
        'id' => 189,
        'phone_code' => '+46',
        'name' => 'Sweden',
        'iso' => 'SE',
        'state_status' => 1,
    ],
    "CH" => [
        'id' => 190,
        'phone_code' => '+41',
        'name' => 'Switzerland',
        'iso' => 'CH',
        'state_status' => 1,
    ],
    "SY" => [
        'id' => 191,
        'phone_code' => '+963',
        'name' => 'Syria',
        'iso' => 'SY',
        'state_status' => 1,
    ],
    "TW" => [
        'id' => 192,
        'phone_code' => '+886',
        'name' => 'Taiwan',
        'iso' => 'TW',
        'state_status' => 1,
    ],
    "TJ" => [
        'id' => 193,
        'phone_code' => '+992',
        'name' => 'Tajikistan',
        'iso' => 'TJ',
        'state_status' => 1,
    ],
    "TZ" => [
        'id' => 194,
        'phone_code' => '+255',
        'name' => 'Tanzania',
        'iso' => 'TZ',
        'state_status' => 1,
    ],
    "TH" => [
        'id' => 195,
        'phone_code' => '+66',
        'name' => 'Thailand',
        'iso' => 'TH',
        'state_status' => 1,
    ],
    "TG" => [
        'id' => 196,
        'phone_code' => '+228',
        'name' => 'Togo',
        'iso' => 'TG',
        'state_status' => 1,
    ],
    "TK" => [
        'id' => 197,
        'phone_code' => '+690',
        'name' => 'Tokelau',
        'iso' => 'TK',
        'state_status' => 1,
    ],
    "TO" => [
        'id' => 198,
        'phone_code' => '+676',
        'name' => 'Tonga',
        'iso' => 'TO',
        'state_status' => 1,
    ],
    "TT" => [
        'id' => 199,
        'phone_code' => '+1868',
        'name' => 'Trinidad and Tobago',
        'iso' => 'TT',
        'state_status' => 1,
    ],
    "TN" => [
        'id' => 200,
        'phone_code' => '+216',
        'name' => 'Tunisia',
        'iso' => 'TN',
        'state_status' => 1,
    ],
    "TR" => [
        'id' => 201,
        'phone_code' => '+90',
        'name' => 'Turkey',
        'iso' => 'TR',
        'state_status' => 1,
    ],
    "TM" => [
        'id' => 202,
        'phone_code' => '+7370',
        'name' => 'Turkmenistan',
        'iso' => 'TM',
        'state_status' => 1,
    ],
    "TC" => [
        'id' => 203,
        'phone_code' => '+1649',
        'name' => 'Turks and Caicos Islands',
        'iso' => 'TC',
        'state_status' => 1,
    ],
    "TV" => [
        'id' => 204,
        'phone_code' => '+688',
        'name' => 'Tuvalu',
        'iso' => 'TV',
        'state_status' => 1,
    ],
    "UG" => [
        'id' => 205,
        'phone_code' => '+256',
        'name' => 'Uganda',
        'iso' => 'UG',
        'state_status' => 1,
    ],
    "UA" => [
        'id' => 206,
        'phone_code' => '+380',
        'name' => 'Ukraine',
        'iso' => 'UA',
        'state_status' => 1,
    ],
    "AE" => [
        'id' => 207,
        'phone_code' => '+971',
        'name' => 'United Arab Emirates',
        'iso' => 'AE',
        'state_status' => 1,
    ],
    "GB" => [
        'id' => 208,
        'phone_code' => '+44',
        'name' => 'United Kingdom',
        'iso' => 'GB',
        'state_status' => 1,
    ],
    "US" => [
        'id' => 209,
        'phone_code' => '+1',
        'name' => 'United States',
        'iso' => 'US',
        'state_status' => 1,
    ],
    "UY" => [
        'id' => 210,
        'phone_code' => '+598',
        'name' => 'Uruguay',
        'iso' => 'UY',
        'state_status' => 1,
    ],
    "UZ" => [
        'id' => 211,
        'phone_code' => '+998',
        'name' => 'Uzbekistan',
        'iso' => 'UZ',
        'state_status' => 1,
    ],
    "VU" => [
        'id' => 212,
        'phone_code' => '+678',
        'name' => 'Vanuatu',
        'iso' => 'VU',
        'state_status' => 1,
    ],
    "VE" => [
        'id' => 213,
        'phone_code' => '+58',
        'name' => 'Venezuela',
        'iso' => 'VE',
        'state_status' => 1,
    ],
    "VN" => [
        'id' => 214,
        'phone_code' => '+84',
        'name' => 'Vietnam',
        'iso' => 'VN',
        'state_status' => 1,
    ],
    "VG" => [
        'id' => 215,
        'phone_code' => '+1284',
        'name' => 'Virgin Islands, British',
        'iso' => 'VG',
        'state_status' => 1,
    ],
    "VI" => [
        'id' => 216,
        'phone_code' => '+1340',
        'name' => 'Virgin Islands, U.s.',
        'iso' => 'VI',
        'state_status' => 1,
    ],
    "WF" => [
        'id' => 217,
        'phone_code' => '+681',
        'name' => 'Wallis and Futuna',
        'iso' => 'WF',
        'state_status' => 1,
    ],
    "YE" => [
        'id' => 218,
        'phone_code' => '+967',
        'name' => 'Yemen',
        'iso' => 'YE',
        'state_status' => 1,
    ],
    "ZM" => [
        'id' => 219,
        'phone_code' => '+260',
        'name' => 'Zambia',
        'iso' => 'ZM',
        'state_status' => 1,
    ],
    "ZW" => [
        'id' => 220,
        'phone_code' => '+263',
        'name' => 'Zimbabwe',
        'iso' => 'ZW',
        'state_status' => 1,
    ],
];     
